name: ROS 2 CI

on:
  push:
    branches: [ humble ]
  pull_request:
    branches: [ humble ]

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    container:
        image: rostooling/setup-ros-docker:ubuntu-jammy-latest
    steps:
      - name: Build and run tests
        uses: ros-tooling/action-ros-ci@0.3.7
        with:
          target-ros2-distro: humble
